In [2]:
import os

os.listdir("/Users/ale/Desktop/MySQL/Project-3/")

['world_happiness_report.csv',
 '.DS_Store',
 'Happiness Indicators.ipynb',
 'Economic Indicators And Inflation.csv',
 'Data Aggregation & Grouping.ipynb',
 'README.md',
 '.git',
 'Economic Indicators.ipynb']

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
happiness_indicators = pd.read_csv('/Users/ale/Desktop/MySQL/Project-3/world_happiness_report.csv')
economic_indicators = pd.read_csv('/Users/ale/Desktop/MySQL/Project-3/Economic Indicators And Inflation.csv')

# Quick check of the data
print(happiness_indicators.head())
print(economic_indicators.head())

  Country  Year  Happiness_Score  GDP_per_Capita  Social_Support  \
0   China  2022             4.39        44984.68            0.53
1      UK  2015             5.49        30814.59            0.93
2  Brazil  2009             4.65        39214.84            0.03
3  France  2019             5.20        30655.75            0.77
4   China  2022             7.28        30016.87            0.05

   Healthy_Life_Expectancy  Freedom  Generosity  Corruption_Perception  \
0                    71.11     0.41       -0.05                   0.83
1                    63.14     0.89        0.04                   0.84
2                    62.36     0.01        0.16                   0.59
3                    78.94     0.98        0.25                   0.63
4                    50.33     0.62        0.18                   0.92

   Unemployment_Rate  ...  Public_Trust  Mental_Health_Index  \
0              14.98  ...          0.34                76.44
1              19.46  ...          0.72                53.38
2              16.68  ...          0.23                82.40
3               2.64  ...          0.68                46.87
4               7.70  ...          0.50                60.38

   Income_Inequality  Public_Health_Expenditure  Climate_Index  \
0              46.06                       8.92          62.75
1              46.43                       4.43          53.11
2              31.03                       3.78          33.30
3              57.65                       4.43          90.59
4              28.54                       7.66          59.33

   Work_Life_Balance  Internet_Access  Crime_Rate  Political_Stability  \
0               8.59            74.40       70.30                 0.29
1               8.76            91.74       73.32                 0.76
2               6.06            71.80       28.99                 0.94
3               6.36            86.16       45.76                 0.48
4               3.00            71.10       65.67                 0.12

   Employment_Rate
0            61.38
1            80.18
2            72.65
3            55.14
4            51.55

[5 rows x 24 columns]
  Country   Year   GDP (in billion USD)   Inflation Rate (%)  \
0     USA   2010                15000.0                 1.64
1     USA   2011                15500.0                 3.16
2     USA   2012                16000.0                 2.07
3     USA   2013                16500.0                 1.50
4     USA   2014                17000.0                 1.62

    Unemployment Rate (%)   Economic Growth (%)
0                    9.63                  2.55
1                    8.94                  1.53
2                    8.10                  2.28
3                    7.70                  1.84
4                    7.25                  2.53

In [4]:
happiness_indicators.columns = (
    happiness_indicators.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('%', 'percent')
    .str.replace('(', '')
    .str.replace(')', '')
)

In [5]:
economic_indicators.columns = (
    economic_indicators.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('%', 'percent')
    .str.replace('(', '')
    .str.replace(')', '')
)

In [26]:
merged_data = pd.merge(
    happiness_indicators,
    economic_indicators,
    on=['country', 'year'],
    how='inner'
)

In [28]:
merged_data.head()

,country,year,happiness_score,gdp_per_capita,social_support,population,urbanization_rate,life_satisfaction,unemployment_rate_percent,economic_growth_percent
0,China,2022,4.39,44984.68,0.53,1311940760,78.71,8.88,5.1,3.3
1,UK,2015,5.49,30814.59,0.93,1194240877,50.87,5.03,5.4,3.1
2,France,2019,5.20,30655.75,0.77,1293957314,81.78,5.69,8.8,1.3
3,China,2022,7.28,30016.87,0.05,1432971455,82.39,6.33,5.1,3.3
4,Germany,2015,7.41,17444.11,0.43,568457305,30.54,5.76,4.7,3.7

In [27]:
columns_to_drop = ['healthy_life_expectancy', 'freedom','unemployment_rate','unemployment_rate', 'employment_rate','mental_health_index','income_inequality','work_life_balance','inflation_rate_percent','political_stability','generosity', 'education_index', 'public_trust', 'public_health_expenditure','corruption_perception', 'climate_index', 'internet_access', 'crime_rate', 'gdp_in_billion_usd']
merged_data.drop(columns=columns_to_drop, inplace=True)

In [43]:
grouped_data = merged_data.groupby(['country', 'year']).mean().round(2).reset_index()
grouped_data.head()

,country,year,happiness_score,gdp_per_capita,social_support,population,urbanization_rate,life_satisfaction,unemployment_rate_percent,economic_growth_percent
0,Australia,2010,5.08,32595.78,0.51,6.090353e+08,52.26,6.04,5.2,2.9
1,Australia,2011,5.81,27194.17,0.48,6.965007e+08,63.53,6.77,5.0,3.1
2,Australia,2012,5.36,27783.72,0.46,6.159698e+08,67.76,6.61,5.1,3.3
3,Australia,2013,5.21,28815.04,0.45,8.527638e+08,54.75,6.88,5.6,2.5
4,Australia,2014,5.95,30691.12,0.51,7.770975e+08,58.50,6.44,5.8,2.9

In [45]:
grouped_data.shape

(135, 10)

In [44]:
grouped_data.isna().sum()

country                      0
year                         0
happiness_score              0
gdp_per_capita               0
social_support               0
population                   0
urbanization_rate            0
life_satisfaction            0
unemployment_rate_percent    0
economic_growth_percent      0
dtype: int64